# Generated by Django 3.0 on 2021-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='Imageurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
