# Generated by Django 3.0 on 2021-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_allproduct_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='Imageurl',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
