# Generated by Django 3.0 on 2021-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20210729_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproduct',
            name='instock',
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='Imageurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
