# Generated by Django 3.0 on 2021-07-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_auto_20210729_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
