# Generated by Django 3.0 on 2021-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='user_profile'),
        ),
    ]
