# Generated by Django 3.0 on 2021-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_auto_20210731_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='photoprofile'),
        ),
    ]
