# Generated by Django 3.0 on 2021-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_cart_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
