# Generated by Django 3.0 on 2021-09-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_auto_20210913_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
