# Generated by Django 3.0 on 2021-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_auto_20210914_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpending',
            name='customer_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
