# Generated by Django 3.0 on 2021-09-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_auto_20210916_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='csrf_anonymous',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
