# Generated by Django 3.0 on 2021-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_orderpending_csrf_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpending',
            name='csrf_anonymous',
        ),
        migrations.AddField(
            model_name='orderpending',
            name='kanom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
