# Generated by Django 3.0 on 2021-09-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_auto_20210921_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='mid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
