# Generated by Django 3.0 on 2021-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_orderpending_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=25, null=True)),
                ('kanom_cookie', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderpending',
            name='mid',
        ),
    ]
