# Generated by Django 3.0 on 2021-09-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_auto_20210922_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messenger',
            new_name='messenger_user',
        ),
    ]
