# Generated by Django 3.0 on 2021-09-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0027_auto_20210922_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger_user',
            name='kanom_cookie',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
