# Generated by Django 3.0 on 2021-09-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_auto_20210923_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger_user',
            name='kanom_cookie',
            field=models.CharField(default='', max_length=50),
        ),
    ]
