# Generated by Django 3.0 on 2021-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_auto_20210923_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messenger_user',
            name='kanom_cookie',
        ),
        migrations.RemoveField(
            model_name='orderpending',
            name='kanom',
        ),
        migrations.AddField(
            model_name='orderpending',
            name='mid',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='messenger_user',
            name='mid',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
