# Generated by Django 3.0 on 2021-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0032_auto_20210923_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
