# Generated by Django 3.0 on 2021-10-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0034_auto_20211001_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
    ]
